[Sparse] Add `clear_triplet()`
dimforge/nalgebra pull request #1141
Opened 2022-08-16 02:29 UTC by lsh

This PR adds the `clear_triplet()` method to the `CooMatrix` struct.
The goal of the method is to be able to remove triplets before construction.

Some outstanding questions:
* Spelling of the method? @Andlon suggested `clear_triplet` in the Discord. Another option might be `pop` or `pop_triplet` to correspond to `push`.
* Should out of bounds values cause a panic? It is probably fine to just return a `None` value.
* What should the return type be? Currently it is `Option<T>`.

2022-08-16 07:02 UTC, Andlon commented
Thanks for working on this @lsh!

Actually, I suggested `clear_triplets` (note plural), for removing *all* triplets. This is very useful as it would allow us to re-use already allocated COO storage and therefore amortize allocations. I'm not so sure if removing a *single* triplet based on coordinates is very useful as it is terribly inefficient - do we have a compelling motivating use case for this?

2022-08-16 07:16 UTC, lsh commented
@Andlon whoops, sorry about my misunderstanding 😅. Updated the code to implement `clear_triplets`.

2022-08-16 09:38 UTC, Andlon commented
@lsh: great, thanks. CI is failing because you have the wrong return type for `clear_triplets`, maybe try running tests locally?

2022-08-19 15:20 UTC, Andlon requested changes
@lsh: just one unnecessary trait bound that needs to be removed, otherwise looks good! Tests are still running but assuming they succeed after removing the trait bound we should be good to go.

2022-08-19 15:20 UTC, Andlon commented on nalgebra-sparse/src/coo.rs
> +        T: PartialEq,
This bound is not necessary

2022-08-19 15:24 UTC, Andlon commented
@sebcrozet: not sure why the CUDA build is failing. Do you? Looks like some strange issues with the recent changes that made `Point::new` a `const fn`?

2022-08-19 15:54 UTC, sebcrozet commented
@Andlon You’re right, looks like https://github.com/dimforge/nalgebra/pull/1112 broke the CUDA build. I think this is due to the fact that the CUDA build uses an older version of the compiler which only allowed `Sized` trait bounds for `const fn`. We should add a non-const version when targeting `cuda`.

2022-08-22 06:41 UTC, Andlon commented
Looks good to me, ready for merge. @sebcrozet: do we wait with merging until the CUDA CI problems are fixed, or what's your preference?

2022-08-22 07:09 UTC, sebcrozet commented
Thank you both! No need to delay this on something unrelated.

2022-08-22 07:09 UTC, merged