Link listed types in lib.rs to their docs
dimforge/nalgebra pull request #1144
Opened 2022-08-19 11:39 UTC by Patiga

Helpful because lib.rs is the 'main page' for docs.rs
This allows for easy/direct access to the mentioned types
Currently you need to look up mentioned types via the search bar

2022-08-29 11:01 UTC, Andlon requested changes
Thanks, this is indeed  very helpful!

I only noticed a missing space, otherwise looks good to me. I didn't try to pull down and builds the docs though - can you verify that the docs indeed render correctly and that the links work?

2022-09-03 22:44 UTC, Patiga commented on src/lib.rs
> +* A single parametrizable type [`Matrix`](Matrix) for vectors, (square or rectangular)matrices, and
Fixed now, good catch :)

2022-09-03 22:46 UTC, Patiga commented
I have tested all the links.
Links that don't work throw a warning with `cargo doc`, maybe that check could be added to the CI.

2022-09-12 07:08 UTC, merged

2022-09-12 07:08 UTC, Andlon commented
Thanks @Patiga!

> I have tested all the links. Links that don't work throw a warning with `cargo doc`, maybe that check could be added to the CI.

That's a good idea, I created #1151 for this purpose.