Introduce Storage::forget() to fix memory leak in Matrix::generic_resize()
dimforge/nalgebra pull request #1379
Opened 2024-04-07 19:11 UTC by nickmertin

Fixes #1378 

Adds a trait method `Storage::forget()` to clean up the storage while forgetting (i.e., not dropping) the contents. Makes use of this method instead of `mem::forget()` in the implementations of `Reallocator` for `DefaultAllocator`.

2024-04-10 15:28 UTC, Andlon commented
Thanks, this is great! I don't have the head space or time to wrap my head around the nuances of the `Reallocator` API here at the moment, but I wanted to ask if the documentation needs to be updated to reflect any possible changes in assumptions made. I don't fully understand them yet myself, I'd need a closer look later to try to verify.

2024-05-06 13:40 UTC, Andlon commented
I haven't forgotten this PR, but I haven't yet been able to devote time to it. It came up on Discord though, and @sebcrozet suggested that the `forget` function needs to be `unsafe`, and maybe it should be called `forget_elements` or something along those lines.

I'll try to get back to this soon, but I suspect I'll be quite busy this week.

2024-05-06 15:21 UTC, nickmertin commented
I like the name `forget_elements`, I think it gets the behaviour across more accurately than what I put right now.

I don't think it should be `unsafe`, for the [same reason that `mem::forget` isn't `unsafe`](https://doc.rust-lang.org/std/mem/fn.forget.html#safety). Safety does not guarantee that destructors are called, so there is nothing unsafe about calling this function. Marking it as `unsafe` would push obligations of ensuring safety onto everywhere it is called, which could be hard to follow given that it is a trait method and there are several implementations. Perhaps the behaviour and safety attributes just need to be better documented, as is the case for `mem::forget`.

2024-05-07 01:00 UTC, tpdickso approved these changes
This looks appropriate to me! And I agree, I think a name like `forget_elements` would be great to help highlight that it's the elements that are being forgotten and not the storage itself (which will be dropped normally absent any other intervention.)

2024-05-09 08:32 UTC, Andlon requested changes
You're absolutely right about the fact that `forget` doesn't have to be `unsafe` @nickmertin! I just have a few minor suggestions, then we can get this merged in time for the next release :)

2024-05-09 08:32 UTC, Andlon commented on src/base/storage.rs
> +    /// Cleans up the storage without calling the destructors on the contained elements.
As discussed, perhaps change the name to `forget_elements`.

I think perhaps "cleans up" is a little vague. Perhaps "Drops the storage without ..." ?

2024-05-09 08:32 UTC, Andlon commented on src/base/vec_storage.rs
> +        // Set length to 0 so element destructors are not called.
Perhaps add a "SAFETY" comment here and explain that `.set_len(0)` always satisfies the invariants of `.set_len`, but the contents are deliberately leaked

(same for other `forget` impl)

the "SAFETY comment" practice is a relatively recent thing, and much of `nalgebra`'s codebase, to my knowledge, predates this convention. But I think we should try to stick with it going forward, whenever it makes sense!

2024-05-09 22:27 UTC, nickmertin commented
Sounds good, I will make the necessary changes this weekend.

2024-05-12 16:45 UTC, nickmertin commented
I believe it is now good to go, let me know if any other changes are needed!

2024-05-13 09:33 UTC, Andlon commented
Thanks @nickmertin, it's ready to merge now. Great to have this bug fixed! I'm not merging immediately because of the breaking change in introducing `forget_elements` to the `Storage` trait. In principle, I think we could merge directly since the `dev` branch already contains unreleased breaking changes, but I'll run it by the others later.

2024-06-23 09:48 UTC, sebcrozet commented
Hey! Thank you for this PR @nickmertin, and @Andlon and @tpdickso for reviews.
I merged this work as part of #1416 since I wasn’t able to rebase this PR on top of `dev` for today’s release. My guess is that [Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) wasn’t checked (and I didn’t want to bother the author on a Sunday).

2024-06-23 09:48 UTC, closed without merging