Fixed a (presumed) typo in documentation in matrix_view.rs
dimforge/nalgebra pull request #1385
Opened 2024-04-22 10:38 UTC by fangs124

Fixed a (presumed) typo in documentation in matrix_view.rs.

Previously it says fixed_view and fixed_slice returns a matrix with `(R::dim(), CView::dim())` consecutive components. I just changed R to RView, because presumably this is a typo.

This is my first time submitting a pull request, and I would be more than happy to take any input.

2024-04-22 18:24 UTC, Ralith requested changes
Thanks for the PR! It looks like the docs you're updating affect functions with `RVIEW`/`CVIEW` const generic parameters, not `RView`/`CView` type parameters.

2024-04-23 00:34 UTC, fangs124 commented
sorry, so should they all say `(RVIEW,CVIEW)` instead of `(RView::dim(), CView::diem())`? If so there's a few other functions on that file that has that typo in the documentation.

2024-04-23 00:41 UTC, Ralith commented
That makes sense to me, at least!

2024-04-23 01:16 UTC, Ralith approved these changes
Thanks!

2024-04-23 01:18 UTC, Ralith commented on src/base/matrix_view.rs
> +        /// Slices this matrix starting at its component `(irow, icol)` and with `(RVIEW,CVIEW)`
nit: space after the `,` here and below

2024-04-23 02:51 UTC, merged