Propagate `mem::MaybeUninit` through the return types of `Allocator::…
dimforge/nalgebra pull request #803
Opened 2020-11-27 04:45 UTC by aweinstock314

…allocate_uninitialized` and `Matrix::new_uninitialized_generic`.

Most call sites still invoke UB through `assume_init`. Said call sites instead invoke `unimplemented!()` if the `no_unsound_assume_init` feature is enabled, to make it easier to gradually fix them.

Progress towards #556.

2020-11-27 16:02 UTC, sebcrozet requested changes
Thank you for this PR! This is a great first step. Some changes:
- The CI tests won't pass unless a `cargo fmt` is run.
- I think for this first PR, we should keep the same behavior as before, i.e., not use the `crate::zero_or_uninitialized_generic!` at all and always use `unimplemented!()` when `no_unsound_assume_init` is enabled. Perhaps define a macro similar to your `zero_or_uninitialized_generic!` but that does an `unimplemented!()` instead of the zero initialization?

2020-11-27 21:16 UTC, aweinstock314 commented
It looks like I missed a few spots from only iterating over `cargo test`, I see the rest of the targets in `.circleci/config.yml` now.

2021-02-25 14:45 UTC, sebcrozet approved these changes

2021-02-25 14:46 UTC, merged

2021-02-25 14:47 UTC, sebcrozet commented
Thank you for this PR! I took the liberty to fix the remaining compilation errors.