Added bytemuck implementations for static storages.
dimforge/nalgebra pull request #831
Opened 2021-02-11 02:49 UTC by iMplode-nZ

See issue #830.

2021-02-24 08:56 UTC, henkkuli commented
I just happened to pass by and noticed this PR and took a quick look. I think the current proposal is unsound as there is no bound on the underlying type being `Zeroable` or `Pod`. In particular, if someone plugs a type containing a `NonZero` into a matrix, the type should not be `Zeroable`.

I think implementing `Zeroable` and `Pod` directly for `Matrix` is quite high in the hierarchy. Arguably we should implement the traits on `ArrayStorage` and then derive the traits for `Matrix` when the storage type implements the traits. One could even argue the traits should be implemented on `generic_array::GenericArray`. Deriving the trait from the underlying type allows the users to implement their own storage type with the traits, and have the matrix still implement the traits.

2021-02-25 09:00 UTC, sebcrozet requested changes
Thank you for this PR!

I agree with the remarks from @henkkuli: we are missing a bound of the scalar type, and these traits should be implemented on the `ArrayStorage` first.

I agree with the fact that it would be even better if that was implemented by `generic-array` too, but I'm OK to just do it on `ArrayStorage` considering we will get rid of `generic-array` soon (when `min-const-generics` lands).

2021-02-25 14:07 UTC, sebcrozet approved these changes

2021-02-25 14:07 UTC, sebcrozet commented
I took the liberty to make the relevant changes. I also added an implementation of bytemuck traits for points.

2021-02-25 14:46 UTC, merged