CooMatrix::reserve added
dimforge/nalgebra pull request #885
Opened 2021-05-02 11:54 UTC by chammika-become

PR for  #881
- Added doc tests as well. 

Note: I've noticed missing doc-tests in some of the APIs. Can add them in future PRs if it helps the documentation.

2021-05-03 10:43 UTC, Andlon requested changes
Thanks for this PR, @chammika-become! Looks good to me, and exactly as intended in #881. I only noticed a couple of very minor grammatical things in the doc comments (I hope I got it correct myself, my English is not flawless).

I think the docs would definitely benefit from some additional doc tests, yes! Would be happy to see additional PRs if you would like to work on this :)

2021-05-03 10:43 UTC, Andlon commented on nalgebra-sparse/src/coo.rs
> +    /// frequent reallocations, in `push` operations.
maybe remove the comma here? ("... frequent reallocations in `push` operations)

2021-05-03 10:43 UTC, Andlon commented on nalgebra-sparse/src/coo.rs
> +    /// Panics if any of the individual allocation of triplet arrays fail.
Perhaps "Panics if any of the individual allocations of triplet arrays fails."

2021-05-03 10:43 UTC, Andlon commented on nalgebra-sparse/src/coo.rs
> +    /// // Reserver capacity in advance
Reserver -> Reserve?

2021-05-04 03:41 UTC, chammika-become commented
Thank you for the corrections. I will pay more attention to grammar next time.

2021-05-04 06:51 UTC, Andlon commented
No worries, as I said they were super minor, and it wouldn't really have been necessary to fix them either, because the meaning was clear. I just prefer fixing them up front, because nobody will bother to fix it later!

2021-05-04 06:52 UTC, Andlon approved these changes

2021-05-09 14:58 UTC, sebcrozet commented
Thanks!

2021-05-09 14:58 UTC, merged