Matrix macro
dimforge/nalgebra pull request #886
Opened 2021-05-03 12:02 UTC by Andlon

This PR introduces four new macros to `nalgebra`. They are available under the (now default) `macros` feature, which makes `nalgebra` export the macros from the procedural macro crate `nalgebra-macros`. The macros are:

- `matrix![]` for constructing fixed-size matrices with a MATLAB-like syntax.
- `dmatrix![]` for constructing *dynamic* matrices with the same syntax as `matrix!`
- `vector![]` for constructing small fixed-size vectors (syntax basically the same as `vec!`)
- `dvector![]` for constructing dynamically allocated vectors with the same syntax as `vector`.

The intention here is to simplify matrix/vector construction by improving readability, ease-of-use and ensuring that the matrix construction is as fast as possible.

Example:

```rust
// Directly constructs an SMatrix<_, 2, 3>
let a = matrix![1, 2, 3;
                4, 5, 6];
```

Benefits over e.g. `MatrixRxC::new` constructors:

- Number of rows and columns are inferred from the data, so that when changing the data (e.g. increasing column count) you don't need to update both the data and the type.
- More succinct and obvious.
- Can be combined with e.g. `#[rustfmt::skip::macros(matrix)]` to prevent `rustfmt` from messing up carefully aligned syntax.
- Works for matrices of any (practical) size, not just those who have `new` constructors.
- Semi-colons clearly delineate where each row begins.

Disadvantages:

- Using the macros adds `syn` and `quote` to the dependency tree. On my 6-7 year old laptop, this adds ~10 secs to clean build compile time. Note that if you use `serde` or possibly some of the other optional dependencies, you might already have `syn`/`quote` in your dependency tree, so you pay effectively no penalty. If users don't need the macro, it's also possible to opt out by disabling the `macros` feature.
- I can't think of any others, but please let me know if I've missed any.

The user guide should probably be updated to accommodate these macros. My suggestion is to make these macros the *de-facto* way of constructing matrices with `nalgebra`.

Resolves #873.

2021-05-03 15:18 UTC, Andlon commented on nalgebra-macros/Cargo.toml
> +
`Cargo.toml` needs some work: more metadata, remove the comments. License term needs to be resolved: Currently there's a discrepancy in that Cargo.toml for `nalgebra` says BSD-3 whereas `LICENSE` is Apache 2.0.

2021-05-04 07:01 UTC, Andlon commented
I'm missing one or more tests that verify that the macros work for all built-in types. I will add this as soon as I have time.

2021-05-04 07:02 UTC, Andlon commented
I'm also missing tests where instead of just numbers, we have arbitrary Rust expressions (though one of the doc tests has something like this). I will add this later too.

2021-05-04 17:40 UTC, Ralith commented
What's the case for `vector![1, 2, 3]` existing as a distinct thing from `matrix![1; 2; 3]`?

2021-05-05 06:37 UTC, Andlon commented
> What's the case for `vector![1, 2, 3]` existing as a distinct thing from `matrix![1; 2; 3]`?

Semantics, mostly. Although a vector is also a matrix, matrices and vectors often play different roles in applications, so at least in my opinion it benefits readability to distinguish them at the syntax level (although you can indeed use `matrix!` to construct vectors as well, if you are so inclined).

Second, `dvector![1, 2, 3]` and `dmatrix![1; 2; 3]` do *not* produce the same type. In the first case, you get `DVector<T>`, in the second case `DMatrix<T>`. It seems to me that for symmetry purposes it is then natural to have `vector!` mirror `dvector!` and `matrix!` mirror `dmatrix!`.

2021-05-05 09:59 UTC, Andlon commented
All right, I finished up the things I wanted to address, so I suppose this PR should be ready now.

2021-05-05 10:08 UTC, sebcrozet commented
Hey @Andlon, this is an amazing PR. I will review this within the next few days.

> The user guide should probably be updated to accommodate these macros. My suggestion is to make these macros the de-facto way of constructing matrices with nalgebra.

I agree. I will take care of this later this month.

2021-05-05 13:10 UTC, Andlon commented
Thanks, @sebcrozet! I also wanted to add that I don't have much experience with proc macros, so if there's any experienced proc macro person with some good suggestions for improvement I'd also be happy to hear about that.

2021-05-06 16:38 UTC, sebcrozet requested changes
Thank you again for this PR. This looks great. I'm not a proc-macro expert myself so I can't really judge the quality of the implementation. But it looks OK to me.

2021-05-06 16:38 UTC, sebcrozet commented on src/base/array_storage.rs
> +}
I would suggest to put this on `matrix.rs`, bellow the impl block containing `from_data_statically_unchecked`.
Perhaps we should add a `TODO` comment saying that this should be removed in favor of `Matrix::from_data` once `const-fn` support generic trait bounds.

2021-05-06 16:38 UTC, sebcrozet commented on src/base/vec_storage.rs
> +}
I would suggest to put this on `matrix.rs`, bellow the impl block containing `from_data_statically_unchecked`.
Perhaps we should add a `TODO` comment saying that this should be removed in favor of `Matrix::from_data` once `const-fn` support generic trait bounds.

2021-05-06 18:36 UTC, Ralith commented
The proc macro stuff LGTM.

2021-05-07 07:21 UTC, Andlon commented
@sebcrozet: I moved the impl blocks, but I needed to add some conditional compilation for the `VecStorage`-related stuff in `matrix.rs`. Not sure if this is the way you prefer it. Let me know if you want it done differently.

@Ralith: thanks for taking a look!

2021-05-09 14:51 UTC, sebcrozet approved these changes

2021-05-09 14:52 UTC, sebcrozet commented
@Andlon Looks greatk thanks!

2021-05-09 14:52 UTC, merged